head(EuStockMarkets)
plot(EuStockMarkets)
class(EuStockMarkets)
frequency(EuStockMarkets)
start(EuStockMarkets)
end(EuStockMarkets)
wind <- window(EuStockMarkets, start=1997, end=1998)
wind
plot(wind)
hist(EuStockMarkets[, 'SMI'], 30)
hist(diff(EuStockMarkets[, 'SMI'], 30))
plot(EuStockMarkets[, 'SMI'], EuStockMarkets[, 'DAX'])
plot(diff(EuStockMarkets[, 'SMI']), diff(EuStockMarkets[, 'DAX']))
plot(lag(diff(EuStockMarkets[, 'SMI']), 1), diff(EuStockMarkets[, 'DAX']))